### ISSUE TITLE
Unused arguments in wm.EditEntities.hideMenu

### ISSUE THREAD

**Issue by Joncom** [phoboslab/Impact#15] opened 2019-04-23 13:08 UTC
https://github.com/phoboslab/Impact/blob/f461c2f4054dac37dea351d8fe3440eae6a2f47e/lib/weltmeister/edit-entities.js#L529

**Comment by gamecubate** [comment] 2019-05-01 11:27
PR #22

**Comment by gamecubate** [comment] 2019-05-01 11:31
Can you do the merge and close this issue?

**Comment by Joncom** [comment] 2019-05-01 12:24
A lot of unrelated white space changes in there..

**Comment by gamecubate** [comment] 2019-05-01 12:45
Not from me. I used vim on the one file and made the one change.

**Comment by gamecubate** [comment] 2019-05-01 13:24
Double-checked and the problem is actually from my side, i.e., the develop branch, created months ago, and inadvertently space-modified by me. Will delete said branch and re-push to master, which will make for cleaner changes. Also, there isn't a need for a develop branch at this stage, given that the issues you raised easily qualify as master hotfixes. Thanks for checking. Will re-push shortly.

**Comment by gamecubate** [comment] 2019-05-01 13:48
New PR. #26

**Closed as completed** 2019-05-02 07:44 UTC
